name: Jekyll Themes
url: http://matt.harzewski.com
description: Insert tagline here

# Set the permalink structure for your pages or themes
permalink: /themes/:title/

# Jekyll plugins – here we use jekyll-paginate
plugins:
  - jekyll-paginate

# For syntax highlighting
highlighter: pygments

# Paginate settings (for blogs / index pages)
paginate: 20
paginate_path: "/page:num/"

# Use kramdown as the Markdown processor (Jekyll default)
markdown: kramdown

exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - vendor
